Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/05/2023
// Seção de Declarações das variáveis 
var numero: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
         PARA numero DE 100 ATE 1 PASSO -1 FACA

ESCREVAL (numero)

fimpara

Fimalgoritmo
